### ISSUE TITLE
vectorizer assert thrown in feat/viz/3 branch

### ISSUE THREAD

**Issue by aheirich** [stanfordhpccenter/soleil-x#3]
aheirich@ubuntu:~/Documents/Legion/software/PSAAP/crossMount/soleil-x/src$ USE_CUDA=0 USE_HDF=0 make
./desugar.py soleil.rg > soleil-desugared.rg
/home/aheirich/Documents/Legion/software/PSAAP//crossMount/legion/language/regent.py -g soleil-desugared.rg -fflow 0 -fopenmp 1 -finner 1 -fcuda 0
ignoring demand pragma at soleil-desugared.rg:452 since the CUDA compiler is unavailable
ignoring demand pragma at soleil-desugared.rg:452 since the CUDA compiler is unavailable
.../crossMount/legion/language/src/regent/vectorize_loops.t:498: assertion failed!
stack traceback:
	[C]: in function 'assert'
	.../crossMount/legion/language/src/regent/vectorize_loops.t:498: in function 'fn'
	src/asdl.lua:18: in function 'map'
	.../crossMount/legion/language/src/regent/vectorize_loops.t:1078: in function 'block'
	.../crossMount/legion/language/src/regent/vectorize_loops.t:1222: in function <.../crossMount/legion/language/src/regent/vectorize_loops.t:1221>
	...AAP/crossMount/legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
	...rossMount/legion/language/src/regent/parallelize_tasks.t:3310: in function 'top_task'
	...rossMount/legion/language/src/regent/parallelize_tasks.t:3322: in function <...rossMount/legion/language/src/regent/parallelize_tasks.t:3316>
	...AAP/crossMount/legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
	...are/PSAAP/crossMount/legion/language/src/regent/passes.t:62: in function <...are/PSAAP/crossMount/legion/language/src/regent/passes.t:48>
	soleil-desugared.rg:471: in main chunk
Makefile:67: recipe for target 'soleil.o' failed
make: *** [soleil.o] Error 1

**Comment by manopapad** [comment]
Moving issue to Legion bug tracker (https://github.com/StanfordLegion/legion/issues/420).
